### ISSUE TITLE
currently have to add bootstrap@5.0.1 as devDependencies in order to compile. 

### ISSUE THREAD

**Issue by gribdesbois** [smarteist/Frontent-Starter-Boilerplate#1]
had to npm install --save-dev bootstrap@5.0.1 to avoid compiling error. really like your boilerplate otherwise. could not figure the logic with other boilerplates found on github, being a beginner with webpack.

**Comment by smarteist** [comment]
Sorry i don't understand your issue clearly. You want to remove bs5 dependency from your project?
