### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by thomashdk** [smarteist/Frontent-Starter-Boilerplate#2]
Images is not being copied from src to image folder in dist. And can´t refference to the images like 

`<img src="./images/pizza.jpg">`

**Comment by wozniaktomasz** [comment]
I have the same issue, but temporary I used relative path and still not know how to cope with images.

index.html: 
`<img src="../assets/images/logo.jpg" alt="" />`

**Comment by smarteist** [comment]
> Images is not being copied from src to image folder in dist. And can´t refference to the images like
> 
> `<img src="./images/pizza.jpg">`

Use html srcsets loader plugin like so: 
```  <img src="${require('./../assets/images/800x500(1).jpg')}" alt="...">```

for more information about this plugin checkout [here](https://github.com/ushu/html-srcsets-loader)

**Comment by wozniaktomasz** [comment]
How to use it in scss files? It seems not working and images are corrupted.

For example, its not generate errors but not working (image is corrupted):
src/assets/styles/layout/_example.scss
`
        .example {
            background-image: url('./../../images/axample.png');
        }
`

**Comment by smarteist** [comment]
> How to use it in scss files? It seems not working and images are corrupted.
> 
> For example, its not generate errors but not working (image is corrupted): src/assets/styles/layout/_example.scss `.example { background-image: url('./../../images/axample.png'); }`

CSS files should be addressed relative to their location in the dist directory like so ```./../images/axample.png```, but if you do not want to do this you can add [this](https://stackoverflow.com/questions/45597788/relative-css-urls-in-webpack) plugin to the webpack.

**Comment by wozniaktomasz** [comment]
Still not working, relative path not generate errors but still not working, imported image appear as white box,
Image file content:
`module.exports = __webpack_public_path__ + "images/example.png"`

**Comment by smarteist** [comment]
> background-image: url('./../../images/axample.png');

Ok, its a configuraiton problem, i've changed the [webpack.config.js](https://github.com/smarteist/Frontent-Starter-Boilerplate/blob/master/webpack.config.js) file, please update image module rules like below:
```
{
          test: /\.(png|svg|jpe?g|gif)$/,
          type: 'asset/resource',
          generator: {
            filename: 'images/[hash][ext]',
          },
},
```
and include images like before ```.example { background-image: url('./../../images/axample.png'); }```
 its now fixed.

**Comment by smarteist** [comment]
@thomashdk @wozniaktomasz This issue completely resolved, you can reference to anything by using this alias ```src/<ANY_DIR>/```, please update yours.
